# 测试配置文件
server:
  port: 8888
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:h2:mem:design
    driver-class-name: org.h2.Driver
    username: design
    password: design
    # 初始化表结构
    schema:
      classpath: classpath:schema.sql
    # 初始化数据
    data:
      classpath: classpath:data.sql
  redis:
    host: localhost
    port: 6379
    password: 123456
  h2:
    console:
      #数据库开启console
      enabled: true
      #通过访问/myH2访问数据库可视化界面
      path: /myH2
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #自动更新ddl
          auto: update
        dialect: org.hibernate.dialect.H2Dialect
    # 控制台打印sql语句
    show-sql: true
    hibernate:
      ddl-auto: none

gitee:
  clientId: 0247f2bbda10a6831e9759b4497b5ba22250de77b46666576f4286b556f5e9fd
  clientSecret: a223408e48ae8a89f1250594f96b09a94fb121abfe2aefe1eb43491e2e301583
  callBack: http://localhost:8888/api/bridge/gitee
  state: GITEE
  user:
    prefix: ${gitee.state}@
    url: https://gitee.com/api/v5/user?access_token=
  token:
    url: https://gitee.com/oauth/token?grant_type=authorization_code&client_id=${gitee.clientId}&client_secret=${gitee.clientSecret}&redirect_uri=${gitee.callBack}&code=
